<?php

require '/usr/share/php/libphp-phpmailer/class.phpmailer.php';
require '/usr/share/php/libphp-phpmailer/class.smtp.php';
/*include 'Library/MAILER/PHPmailer.php';*/

$mail = new PHPMailer;
$mail->setFrom('info@abcs.com.tn');
$mail->addAddress('dridihatem@gmail.com');
$mail->Subject = 'Message sent by PHPMailer';
$mail->Body = '<h2>Hello!</h2><p style="color:Blue;">
I am using PHPMailer to send email</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'tls';
$mail->Host = 'serv7.zenhosting.info';
$mail->SMTPAuth = true;
$mail->Port = 587;
$mail->Username = 'info@abcs.com.tn';
$mail->Password = 'AhHSef$%Ttg(';
if(!$mail->Send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  echo 'Email has been sent.';
}
?>
